name: 🧰 Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "7 7 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  nightly:
    name: 🌙 Nightly Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --locked --all-features --all-targets --workspace

  update:
    name: 🔄 Latest Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@beta
      - run: cargo update
      - run: RUSTFLAGS="-D deprecated" cargo test --locked --all-features --all-targets --workspace
